In [4]:
import torch

In [8]:
y = torch.randn(10)
x = torch.randn(10, requires_grad=True)

x

tensor([-0.8167, -0.6518,  0.8443, -0.9945, -0.2967, -0.9750,  0.0497,  0.1729,
        -0.3147, -0.5616], requires_grad=True)

In [11]:
(y**2).mean()

tensor(0.8565)

In [12]:
b = (x**2).mean()
print(b)
b.backward()

tensor(0.4279, grad_fn=<MeanBackward0>)


In [15]:
print(x / 10 * 2)
print(x.grad)

tensor([-0.1633, -0.1304,  0.1689, -0.1989, -0.0593, -0.1950,  0.0099,  0.0346,
        -0.0629, -0.1123], grad_fn=<MulBackward0>)
tensor([-0.1633, -0.1304,  0.1689, -0.1989, -0.0593, -0.1950,  0.0099,  0.0346,
        -0.0629, -0.1123])


In [16]:
torch.cuda.memory_allocated()

0

In [17]:
x = torch.randn(2**20, requires_grad=True, device='cuda')
torch.cuda.memory_allocated() / 1024 / 1024   

4.0

In [21]:
b = x
for _ in range(100):
    b = torch.relu(b)
torch.cuda.memory_allocated() / 1024 / 1024   

404.0

In [22]:
b.sum().backward()
torch.cuda.memory_allocated() / 1024 / 1024   

12.0