In [1]:
import torch
import torch.distributions as dist

In [9]:
# Bernoulli distribution

bernoulli = dist.Bernoulli((torch.tensor([0.5])))
print(bernoulli)
for _ in range(10):
    print(bernoulli.sample())

Bernoulli(probs: tensor([0.5000]))
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])


In [11]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.mean((torch.stack(samples)))}")
print(f"Varience: {torch.var((torch.stack(samples)))}")

Mean: 0.5070000290870667
Varience: 0.25020119547843933


In [16]:
# Normal distribution
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
for _ in range(10):
    print(normal.sample())

tensor([-0.3380])
tensor([-0.0534])
tensor([2.0818])
tensor([0.8129])
tensor([-0.2826])
tensor([-2.1263])
tensor([0.0163])
tensor([-1.0069])
tensor([-1.3732])
tensor([-0.9342])


In [20]:
samples = [normal.sample() for _ in range(1000)]
print(f"Mean: {torch.mean((torch.stack(samples)))}")
print(f"Varience: {torch.var((torch.stack(samples)))}")

Mean: 0.016579801216721535
Varience: 0.9836633801460266
