In [1]:
import torch

## Recap with Datasets 
$D = \{(x_i, y_i)\}_{i=1}^{N} \quad \text{where} \quad (x_i, y_i) \sim P(X, Y)$

#### Loss function:
$l(\theta | x_i, y_i)$

#### Expected loss:
$L(\theta | D) = \mathbb{E}_{(x,y) \sim D} [l(\theta | x, y)]$


We optimize the expected loss

Here we have a simple linear model with 10 inputs and 1 output

In [2]:
model = torch.nn.Linear(10, 1)

Generate 20 samples, each with 10 features. And also 20 labels.

In [3]:
x = torch.randn(20, 10)
y = torch.randn(20, 1)
print(f'{x=} {y=}')

x=tensor([[-0.2375, -0.8723,  0.5362,  0.7903, -0.0491,  0.9922, -2.5445, -0.4925,
          0.8618, -0.3821],
        [-0.3174,  0.2866, -0.1397,  0.8998, -0.6633,  0.4263,  0.7927, -1.4362,
         -2.0186,  0.3300],
        [ 1.6627,  0.4237,  0.9898,  1.1566, -0.3990,  0.4905, -1.5666,  1.1104,
          0.0129, -1.1409],
        [-0.6615,  0.3606,  0.3081, -0.5272, -0.1831,  0.1797, -0.8463, -1.4233,
         -0.3656, -0.2409],
        [ 2.0652,  0.0823,  0.4148,  0.3738, -0.8232,  0.2528, -0.4196,  0.3449,
         -0.6813, -0.0383],
        [-0.4550, -1.3191, -0.5685,  0.4255, -0.9612, -0.2849,  1.7180, -2.3235,
          1.3412,  0.3782],
        [ 1.1008,  0.1599, -0.4455, -0.4049, -0.5067, -0.7895,  0.0854,  0.3949,
         -1.1136, -0.1814],
        [ 2.0084, -1.2943,  2.0866,  0.9067,  1.3827, -0.4147, -1.6592, -0.9102,
         -1.4861, -1.1408],
        [ 0.5492,  0.0761,  0.9751, -0.1177,  1.1501, -0.4688, -1.0472,  0.3772,
         -0.6103, -0.6961],
        [-2.4141,

Pass through model with x, we get predictions for y.

In [4]:
pred_y = model(x)
print(pred_y)

tensor([[-0.5258],
        [-0.8593],
        [ 0.0161],
        [-0.5969],
        [-0.0445],
        [-0.0775],
        [-0.1613],
        [-0.4886],
        [-0.3789],
        [-0.8068],
        [-0.2842],
        [ 0.1432],
        [-0.8723],
        [-0.4012],
        [-0.4084],
        [ 0.5388],
        [-0.4569],
        [-0.3897],
        [-0.3761],
        [-0.6417]], grad_fn=<AddmmBackward0>)


**Mean Squared Error (MSE) Formula**

The Mean Squared Error (MSE) measures the average squared difference between actual and predicted values:


$MSE = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2$

A lower MSE indicates a better fit of the model.


In [5]:
loss = torch.nn.functional.mse_loss(pred_y, y)
print(loss)

tensor(1.3900, grad_fn=<MseLossBackward0>)


MSE from scratch

In [6]:
def mse_loss(pred_y, y):
    return torch.mean((pred_y - y) ** 2)
mse_loss(pred_y, y)

tensor(1.3900, grad_fn=<MeanBackward0>)

Let's create 20 binary labels 

In [7]:
y = (torch.randn(20, 1) > 0).float()
print(y)

tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])


### Binary Cross Entropy with Logits (BCE with Logits)

Binary Cross Entropy with Logits is used for binary classification tasks. Instead of working with probabilities, it takes raw model outputs (logits) and applies the **sigmoid function** internally for stability.

#### **Formula:**
$
L = -\frac{1}{n} \sum_{i=1}^{n} \left[ y_i \log(\sigma(\hat{y}_i)) + (1 - y_i) \log(1 - \sigma(\hat{y}_i)) \right]
$


Using logits instead of probabilities improves numerical stability and gradient computations.


In [8]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_y, y)
print(loss)

tensor(0.6922, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


Let's create a new model that takes in 10 inputs and outputs 3 different classes

Let's also create some labels of classes 0 - 2

In [9]:
num_classes = 3
model = torch.nn.Linear(10, num_classes)
y = (torch.randn(20) > 0).long() + (torch.randn(20) > 0).long()
print(y)

tensor([1, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1])


### Cross Entropy Loss

Cross Entropy is used for classification tasks to compare the predicted probability distribution with the true class labels.

**Formula for a Single Sample:**

$L = -\sum_{i=1}^{C} y_i \log(\hat{y}_i)$

**Formula for Multiple Samples:**

$L = -\frac{1}{n} \sum_{j=1}^{n} \sum_{i=1}^{C} y_{j,i} \log(\hat{y}_{j,i})$


Cross entropy penalizes incorrect predictions more severely when the confidence in a wrong class is high.


In [ ]:
pred_y = model(x)
loss = torch.nn.functional.cross_entropy(pred_y, y)
print(loss)

tensor(1.0760, grad_fn=<NllLossBackward0>)
