In [2]:
import torch

In [3]:
model = torch.nn.Linear(10, 1)

In [6]:
x = torch.randn(20, 10)
y = torch.randn(20, 1)
print(f'{x=} {y=}')

x=tensor([[-6.5730e-01,  1.1809e-01, -8.2522e-01, -1.4412e+00,  1.1921e+00,
          1.4686e+00,  1.6394e-01,  6.0197e-01, -1.1843e+00,  2.7415e-01],
        [ 7.7028e-01, -1.1873e+00,  6.2441e-02,  1.3352e+00, -2.1453e-01,
          6.3116e-01, -3.6455e-01, -1.7704e-02,  1.2703e+00,  8.9349e-01],
        [-3.9517e-01,  4.9075e-01, -3.0538e-01, -1.8162e+00,  3.1262e-01,
          4.9967e-01,  6.3155e-01, -9.8313e-01, -1.3401e+00,  4.2902e-01],
        [-1.0603e+00, -4.6727e-01, -7.2097e-01, -1.1275e+00, -9.5027e-01,
         -4.7162e-01,  1.2196e+00, -8.4572e-01,  5.1249e-01,  6.1929e-02],
        [-1.8177e+00,  4.6612e-01, -9.9955e-01, -9.3522e-01, -2.1072e-01,
          1.7697e-01,  3.8444e-01,  1.8035e+00, -7.1695e-01, -2.0488e-01],
        [-1.7819e-02,  1.2501e-01,  1.1214e+00, -4.4731e-01, -7.9744e-01,
         -5.9909e-01,  3.6898e-01, -7.9096e-01,  1.1368e+00,  8.4311e-01],
        [ 1.3195e+00,  8.4285e-01,  7.2818e-01, -5.9617e-01,  6.6420e-01,
          1.0336e+00, -5.6625e

In [8]:
pred_y = model(x)
print(pred_y)

tensor([[-0.0614],
        [-0.2247],
        [ 0.1690],
        [ 0.7200],
        [ 0.5917],
        [ 0.3289],
        [ 0.0827],
        [ 0.2841],
        [ 0.5551],
        [-0.3508],
        [ 0.4898],
        [ 0.2272],
        [-0.3268],
        [-1.1392],
        [-0.6167],
        [ 0.6097],
        [-0.1426],
        [-0.2076],
        [ 0.0206],
        [-0.0318]], grad_fn=<AddmmBackward0>)


In [10]:
loss = torch.nn.functional.mse_loss(pred_y, y)
print(loss)

tensor(1.1833, grad_fn=<MseLossBackward0>)


In [11]:
def mse_loss(pred_y, y):
    return torch.mean((pred_y - y) ** 2)
mse_loss(pred_y, y)

tensor(1.1833, grad_fn=<MeanBackward0>)

In [12]:
y = (torch.randn(20, 1) > 0).float()
print(y)

tensor([[0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])


In [13]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_y, y)
print(loss)

tensor(0.7696, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [17]:
num_classes = 3
model = torch.nn.Linear(10, num_classes)
y = (torch.randn(20) > 0).long() + (torch.randn(20) > 0).long()
print(y)

tensor([1, 2, 2, 2, 0, 2, 1, 0, 1, 1, 0, 0, 1, 1, 2, 2, 2, 1, 1, 2])


In [19]:
pred_y = model(x)
loss = torch.nn.functional.cross_entropy(pred_y, y)
print(loss)

tensor(1.0760, grad_fn=<NllLossBackward0>)
