In [1]:
import torch

In [5]:
a = torch.tensor([1.0, 2, 3])
print(a.dtype)
print(a.shape)
print(a.ndim)

torch.float32
torch.Size([3])
1


In [6]:
b = torch.zeros([3, 3, 3], dtype=torch.float32)
print(b)
print(b.ndim)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
3


In [9]:
b = torch.ones([3, 3, 3], dtype=torch.float32)
print(b)
print(b.ndim)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
3


In [8]:
b = torch.rand([3, 3, 3], dtype=torch.float32)
print(b)
print(b.ndim)

tensor([[[0.0586, 0.3647, 0.6618],
         [0.9095, 0.8112, 0.7776],
         [0.9628, 0.8881, 0.1162]],

        [[0.8154, 0.8022, 0.7376],
         [0.3134, 0.3768, 0.1080],
         [0.3278, 0.5900, 0.2483]],

        [[0.5804, 0.3347, 0.8118],
         [0.2095, 0.3694, 0.3710],
         [0.7794, 0.9695, 0.5391]]])
3


In [15]:
from PIL import Image
import numpy as np

img = Image.open('cat.jpg')
c = torch.as_tensor(np.array(img))
print(c)
print(c.shape)
print(c.ndim)

tensor([[[ 96,  99,  90],
         [ 96,  99,  92],
         [ 96,  99,  92],
         ...,
         [110, 100,  98],
         [109,  99,  97],
         [109,  99,  97]],

        [[ 96,  99,  90],
         [ 96,  99,  92],
         [ 96,  99,  92],
         ...,
         [107,  99,  96],
         [108,  98,  96],
         [109,  99,  97]],

        [[ 96,  97,  89],
         [ 96,  97,  91],
         [ 97,  98,  92],
         ...,
         [103,  95,  92],
         [105,  97,  94],
         [106,  98,  95]],

        ...,

        [[ 67, 132,  89],
         [ 68, 133,  90],
         [ 69, 134,  91],
         ...,
         [ 90, 159, 115],
         [ 91, 160, 116],
         [ 91, 160, 116]],

        [[ 70, 139,  94],
         [ 71, 140,  95],
         [ 71, 140,  95],
         ...,
         [ 92, 161, 117],
         [ 93, 162, 118],
         [ 94, 161, 118]],

        [[ 70, 146,  99],
         [ 71, 147, 100],
         [ 70, 146,  99],
         ...,
         [ 95, 162, 119],
        

In [19]:
a = torch.arange(10)
b = torch.ones(10)
print(f'{a = }')
print(f'{b = }')
print(f'{a + b = }')
print(a * b)

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
a + b = tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [21]:
a = torch.rand(1_000_000)
b = torch.rand(1_000_000)
c = a + b

In [22]:
%timeit c = a + b

96.5 μs ± 9.97 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [23]:
a_gpu = a.to('cuda')
b_gpu = b.to('cuda')
%timeit c_gpu = a_gpu + b_gpu

13.2 μs ± 276 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
a = torch.arange(6)
print(a.view(2, 3))
print(a.ndim)
# left off 12:20

tensor([[0, 1, 2],
        [3, 4, 5]])
1
