In [2]:
import torch

In [5]:
a = torch.tensor([1.0, 2, 3])
print(a.dtype)
print(a.shape)
print(a.ndim)

torch.float32
torch.Size([3])
1


In [6]:
b = torch.zeros([3, 3, 3], dtype=torch.float32)
print(b)
print(b.ndim)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
3


In [9]:
b = torch.ones([3, 3, 3], dtype=torch.float32)
print(b)
print(b.ndim)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
3


In [8]:
b = torch.rand([3, 3, 3], dtype=torch.float32)
print(b)
print(b.ndim)

tensor([[[0.0586, 0.3647, 0.6618],
         [0.9095, 0.8112, 0.7776],
         [0.9628, 0.8881, 0.1162]],

        [[0.8154, 0.8022, 0.7376],
         [0.3134, 0.3768, 0.1080],
         [0.3278, 0.5900, 0.2483]],

        [[0.5804, 0.3347, 0.8118],
         [0.2095, 0.3694, 0.3710],
         [0.7794, 0.9695, 0.5391]]])
3


In [15]:
from PIL import Image
import numpy as np

img = Image.open('cat.jpg')
c = torch.as_tensor(np.array(img))
print(c)
print(c.shape)
print(c.ndim)

tensor([[[ 96,  99,  90],
         [ 96,  99,  92],
         [ 96,  99,  92],
         ...,
         [110, 100,  98],
         [109,  99,  97],
         [109,  99,  97]],

        [[ 96,  99,  90],
         [ 96,  99,  92],
         [ 96,  99,  92],
         ...,
         [107,  99,  96],
         [108,  98,  96],
         [109,  99,  97]],

        [[ 96,  97,  89],
         [ 96,  97,  91],
         [ 97,  98,  92],
         ...,
         [103,  95,  92],
         [105,  97,  94],
         [106,  98,  95]],

        ...,

        [[ 67, 132,  89],
         [ 68, 133,  90],
         [ 69, 134,  91],
         ...,
         [ 90, 159, 115],
         [ 91, 160, 116],
         [ 91, 160, 116]],

        [[ 70, 139,  94],
         [ 71, 140,  95],
         [ 71, 140,  95],
         ...,
         [ 92, 161, 117],
         [ 93, 162, 118],
         [ 94, 161, 118]],

        [[ 70, 146,  99],
         [ 71, 147, 100],
         [ 70, 146,  99],
         ...,
         [ 95, 162, 119],
        

In [19]:
a = torch.arange(10)
b = torch.ones(10)
print(f'{a = }')
print(f'{b = }')
print(f'{a + b = }')
print(a * b)

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
a + b = tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [21]:
a = torch.rand(1_000_000)
b = torch.rand(1_000_000)
c = a + b

In [22]:
%timeit c = a + b

96.5 μs ± 9.97 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [23]:
a_gpu = a.to('cuda')
b_gpu = b.to('cuda')
%timeit c_gpu = a_gpu + b_gpu

13.2 μs ± 276 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
a = torch.arange(6)
print(a.view(2, 3))
print(a.ndim)

tensor([[0, 1, 2],
        [3, 4, 5]])
1


In [14]:
a = torch.rand(2, 3, 4)
print(a)

# matrix transpose
print(a.mT)

tensor([[[0.4532, 0.7569, 0.3373, 0.7323],
         [0.9414, 0.2116, 0.3641, 0.4078],
         [0.8139, 0.1865, 0.3362, 0.2307]],

        [[0.2094, 0.5534, 0.2909, 0.1421],
         [0.1906, 0.5286, 0.7439, 0.7436],
         [0.9621, 0.2885, 0.0410, 0.5784]]])
tensor([[[0.4532, 0.9414, 0.8139],
         [0.7569, 0.2116, 0.1865],
         [0.3373, 0.3641, 0.3362],
         [0.7323, 0.4078, 0.2307]],

        [[0.2094, 0.1906, 0.9621],
         [0.5534, 0.5286, 0.2885],
         [0.2909, 0.7439, 0.0410],
         [0.1421, 0.7436, 0.5784]]])


In [15]:
a = torch.rand(2, 3, 4)
b = a.permute(1, 2, 0)
print(b.shape)

torch.Size([3, 4, 2])


In [ ]:
a = torch.arange(6)
print(a)
print(a[..., None, None, None].shape)

tensor([0, 1, 2, 3, 4, 5])
torch.Size([6, 1, 1, 1])
tensor([0, 1, 2, 3, 4, 5])


In [ ]:
a = torch.arange(6).view(3, 2, 1, 1)
print(a.squeeze(-1).shape)

# You should never have to call .squeeze() with no args
print(a.squeeze().shape)

torch.Size([3, 2, 1])
torch.Size([3, 2])


In [ ]:
# Broadcasting
a = torch.rand(4, 1)
b = torch.rand(1, 5)
print(a + b)

tensor([[1.1765, 0.4587, 0.7654, 0.7444, 0.7554],
        [0.9047, 0.1868, 0.4935, 0.4726, 0.4835],
        [0.8541, 0.1363, 0.4430, 0.4221, 0.4330],
        [1.3893, 0.6714, 0.9781, 0.9572, 0.9681]])


In [ ]:
# Squared Euclidean distance
x = torch.randn(100, 2)
d = torch.zeros(100, 100)
for i in range(100):
    for j in range(100):
        d[i, j] = (x[i] - x[j]).pow(2).sum()


d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)
print(d)

tensor([[ 0.0000,  1.3203,  0.9255,  ...,  3.4268,  3.7630,  2.9969],
        [ 1.3203,  0.0000,  0.5641,  ...,  6.0594,  0.8373,  7.1734],
        [ 0.9255,  0.5641,  0.0000,  ...,  2.9888,  2.7225,  4.2364],
        ...,
        [ 3.4268,  6.0594,  2.9888,  ...,  0.0000, 11.3814,  0.7603],
        [ 3.7630,  0.8373,  2.7225,  ..., 11.3814,  0.0000, 12.7770],
        [ 2.9969,  7.1734,  4.2364,  ...,  0.7603, 12.7770,  0.0000]])


In [ ]:
# Find max distance
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
max_dist, max_idx, = 0, (-1, -1)
for i in range(10):
    for j in range(10):
        if(x[i] - x[j]).pow(2).sum() > max_dist:
            max_dist, max_idx = (x[i] - x[j]).pow(2).sum(), (i, j)

print(max_dist, max_idx)


d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)
print(d.max(), (d.argmax() // 10, d.argmax() % 10))

tensor(13.8901) (4, 7)
tensor(13.8901) (tensor(4), tensor(7))


In [43]:
a = torch.rand(2, 4)
b = torch.rand(4, 3)
c = a @ b
print(c.shape)
print(torch.linalg.norm(b))
print(b.pow(2).sum().sqrt())

torch.Size([2, 3])
tensor(2.3103)
tensor(2.3103)
