In [1]:
import torch

In [2]:
y = torch.randn(10)
x = torch.randn(10, requires_grad=True)

x

tensor([-0.0661, -0.4358,  0.1438,  1.6708,  2.9624,  1.5342,  0.7558,  0.1996,
        -1.2178, -1.8280], requires_grad=True)

In [3]:
(y**2).mean()

tensor(1.9681)

In [4]:
b = (x**2).mean()
print(b)
b.backward()

tensor(1.9572, grad_fn=<MeanBackward0>)


In [5]:
print(x / 10 * 2)
print(x.grad)

tensor([-0.0132, -0.0872,  0.0288,  0.3342,  0.5925,  0.3068,  0.1512,  0.0399,
        -0.2436, -0.3656], grad_fn=<MulBackward0>)
tensor([-0.0132, -0.0872,  0.0288,  0.3342,  0.5925,  0.3068,  0.1512,  0.0399,
        -0.2436, -0.3656])


In [13]:
torch.cuda.memory_allocated()

12582912

In [14]:
x = torch.randn(2**20, requires_grad=True, device='cuda')
torch.cuda.memory_allocated() / 1024 / 1024   

16.0

In [15]:
b = x
for _ in range(100):
    b = torch.relu(b)
torch.cuda.memory_allocated() / 1024 / 1024   

404.0

In [16]:
b.sum().backward()
torch.cuda.memory_allocated() / 1024 / 1024   

12.0

In [ ]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2 + 3 * x + 1

print("y:", y)

y.backward()

print("x.grad:", x.grad)  

print("y.grad_fn:", y.grad_fn)
print("x.grad_fn:", x.grad_fn)  